export const APP_ORIGIN = '__SAKINAH_APP_ORIGIN__';
export const CONTEXT_MENU_ID = 'sakinah-reflect-selection';
export const EXTENSION_HANDOFF_RESULT_MESSAGE_TYPE = 'SAKINAH_EXTENSION_HANDOFF_RESULT';
export const EXTENSION_REFLECT_MESSAGE_TYPE = 'SAKINAH_EXTENSION_REFLECT';
export const EXTENSION_SHOW_POPOVER_MESSAGE_TYPE = 'SAKINAH_EXTENSION_SHOW_POPOVER';
export const EXTENSION_CONFIRM_REQUEST_MESSAGE_TYPE = 'SAKINAH_EXTENSION_CONFIRM_REQUEST';
export const EXTENSION_INFER_FEELING_MESSAGE_TYPE = 'SAKINAH_EXTENSION_INFER_FEELING';
export const EXTENSION_INFER_FEELING_STREAM_EVENT_MESSAGE_TYPE =
  'SAKINAH_EXTENSION_INFER_FEELING_STREAM_EVENT';
export const QUERY_REQUEST_KEY = 'request';
export const QUERY_SOURCE_KEY = 'source';
export const QUERY_SOURCE_VALUE = 'extension';
export const REQUEST_TTL_MS = 15 * 60 * 1000;
export const STORAGE_KEY = 'sakinah_extension_state';
